// Copyright 2024 The GUAC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package eol

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/guacsec/guac/pkg/certifier"
	"github.com/guacsec/guac/pkg/certifier/attestation"
	"github.com/guacsec/guac/pkg/certifier/components/root_package"
	"github.com/guacsec/guac/pkg/clients"
	"github.com/guacsec/guac/pkg/handler/processor"
	attestationv1 "github.com/in-toto/attestation/go/v1"
	"golang.org/x/time/rate"
)

var (
	eolAPIBase                   = "https://endoflife.date/api"
	ErrEOLComponenetTypeMismatch = errors.New("rootComponent type is not []*root_package.PackageNode")
)

const (
	EOLCollector   = "endoflife.date"
	rateLimit      = 10
	rateLimitBurst = 1
)

type eolCertifier struct {
	client *http.Client
}

type CycleData struct {
	Cycle             string `json:"cycle"`
	ReleaseDate       string `json:"releaseDate"`
	EOL               string `json:"eol"`
	Latest            string `json:"latest"`
	LatestReleaseDate string `json:"latestReleaseDate"`
	LTS               bool   `json:"lts"`
}
type EOLData = []CycleData

func NewEOLCertifier() certifier.Certifier {
	limiter := rate.NewLimiter(rate.Every(time.Second/time.Duration(rateLimit)), rateLimitBurst)
	client := &http.Client{
		Transport: clients.NewRateLimitedTransport(http.DefaultTransport, limiter),
	}
	return &eolCertifier{client: client}
}

// CertifyComponent takes in the root component from the gauc database and does a recursive scan
// to generate EOL attestations
func (e *eolCertifier) CertifyComponent(ctx context.Context, rootComponent interface{}, docChannel chan<- *processor.Document) error {
	packageNodes, ok := rootComponent.([]*root_package.PackageNode)
	if !ok {
		return ErrEOLComponenetTypeMismatch
	}

	var purls []string
	for _, node := range packageNodes {
		purls = append(purls, node.Purl)
	}

	if _, err := EvaluateEOLResponse(ctx, e.client, purls, docChannel); err != nil {
		return fmt.Errorf("could not generate document from OSV results: %w", err)
	}
	return nil
}

// EvaluateEOLResponse takes a list of purls and queries the endoflife.date API to generate EOL attestations
func EvaluateEOLResponse(ctx context.Context, client *http.Client, purls []string, docChannel chan<- *processor.Document) ([]*processor.Document, error) {
	packMap := map[string]bool{}

	products, err := fetchAllProducts(ctx, client)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch all products: %w", err)
	}
	// product map for easy lookup
	productMap := make(map[string]interface{})
	for _, product := range products {
		productMap[product] = true
	}

	for _, purl := range purls {
		// skip any purls that are generated by GUAC as they will not be found in OSV
		if strings.Contains(purl, "pkg:guac") {
			continue
		}
		// skip any purls that have already been processed
		if _, ok := packMap[purl]; !ok {
			// make sure the purl exists in the endoflife.date API
			if _, ok := productMap[purl]; !ok {
				continue
			}
			eolData, err := fetchProductEOL(ctx, client, purl)
			if err != nil {
				return nil, fmt.Errorf("failed to fetch EOL data for %s: %w", purl, err)
			}
		}
		packMap[purl] = true
	}

	responseMap := make(map[string]*osv_scanner.MinimalResponse)
	for i, query := range query.Queries {
		response := resp.Results[i]
		purl := query.Package.PURL

		responseMap[purl] = &response
	}
	return generateDocument(responseMap, docChannel)
}

func fetchAllProducts(ctx context.Context, client *http.Client) ([]string, error) {
	resp, err := client.Get(fmt.Sprintf("%s/all.json", eolAPIBase))
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var products []string
	if err := json.NewDecoder(resp.Body).Decode(&products); err != nil {
		return nil, err
	}

	return products, nil
}

func fetchProductEOL(ctx context.Context, client *http.Client, product string) (EOLData, error) {
	resp, err := client.Get(fmt.Sprintf("%s/%s.json", eolAPIBase, product))
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var eolData EOLData
	if err := json.NewDecoder(resp.Body).Decode(&eolData); err != nil {
		return nil, err
	}

	return eolData, nil
}

// generateDocument generated the processor document for ingestion
func generateDocument(cycleData []CycleData, docChannel chan<- *processor.Document) ([]*processor.Document, error) {
	var generatedOSVDocs []*processor.Document
	for purl, response := range responseMap {
		currentTime := time.Now()
		payload, err := json.Marshal(createAttestation(purl, response.Vulns, currentTime))
		if err != nil {
			return nil, fmt.Errorf("unable to marshal attestation: %w", err)
		}

		doc := &processor.Document{
			Blob:   payload,
			Type:   processor.DocumentEOL,
			Format: processor.FormatJSON,
			SourceInformation: processor.SourceInformation{
				Collector:   EOLCollector,
				Source:      EOLCollector,
				DocumentRef: fmt.Sprintf("%s/%s.json", eolAPIBase, product),
			},
		}
		if docChannel != nil {
			docChannel <- doc
		}
		generatedOSVDocs = append(generatedOSVDocs, doc)
	}
	return generatedOSVDocs, nil
}

// createAttestation generates the EOL attestation
func createAttestation(purl string, eolDate string) *attestation.EOLStatement {
	attestation := &attestation.EOLStatement{
		Statement: attestationv1.Statement{
			Type:          attestationv1.StatementTypeUri,
			PredicateType: attestation.PredicateEOL,
		},
		Predicate: attestation.EOLPredicate{
			EOL: eolDate,
		},
	}

	subject := &attestationv1.ResourceDescriptor{Uri: purl}
	attestation.Statement.Subject = append(attestation.Statement.Subject, subject)

	return attestation
}
